import type { EventCategory, EventTemplate } from "./event-types";

/** Scenario Library events — V1 GA catalog (NORMAL effects only at runtime) */
export const EVENT_CATALOG: EventTemplate[] = [
  {
    eventId: "EVT-001",
    title: "원화 급격 약세",
    description: "글로벌 달러 강세로 수입 원자재·장비 비용이 상승한다.",
    category: "환율",
    educationPurpose: "환율은 구매·COGS·마진에 동시 영향 — 헷지·조달 다변화 개념",
    learningPoints: ["환율은 구매·COGS·마진에 동시 영향", "헷지·조달 다변화 개념"],
    discussionQuestions: ["수입 지역 비중을 줄일 것인가, 가격 전가할 것인가?"],
    normalEffects: [
      { key: "exchangeRate", mode: "PERCENT", value: 12 },
      { key: "rawMaterialIndex", mode: "PERCENT", value: 6 },
      { key: "logisticsCostMultiplier", mode: "MULTIPLY", value: 1.05 },
    ],
    relatedSteps: ["MATERIAL", "SALES", "SETTLEMENT"],
    severity: 3,
    difficulty: "NORMAL",
    tags: ["FX", "import"],
    recommendedPeriod: ["Y1H2", "Y2H1", "Y2H2", "Y3H1", "Y3H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-002",
    title: "엔화·위안 동반 약세 (아시아)",
    description: "아시아 통화 약세로 아시아 경쟁사 수출 가격이 유리해진다.",
    category: "환율",
    educationPurpose: "경쟁 환율 vs 본사 functional currency · 지역별 mix",
    learningPoints: ["경쟁 환율 vs 본사 functional currency", "지역별 mix"],
    discussionQuestions: ["아시아 판매 가격을 인하할 것인가?"],
    normalEffects: [
      { key: "exchangeRate", mode: "PERCENT", value: 5 },
      { key: "marketDemandIndex", mode: "PERCENT", value: -8 },
      { key: "marketSupplyIndex", mode: "PERCENT", value: 10 },
    ],
    relatedSteps: ["SALES", "MATERIAL"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["FX", "ASIA"],
    recommendedPeriod: ["Y1H2", "Y2H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-005",
    title: "기준금리 인상",
    description: "중앙은행 긴축, 차입 비용 상승.",
    category: "금리",
    educationPurpose: "Step1 차입과 Step7 이자비용 연결",
    learningPoints: ["Step1 차입과 Step7 이자비용 연결"],
    discussionQuestions: ["고부채 팀의 대응은?"],
    normalEffects: [
      { key: "interestRateLoan", mode: "DELTA", value: 3 },
      { key: "interestRateDeposit", mode: "DELTA", value: 1 },
      { key: "marketDemandIndex", mode: "PERCENT", value: -5 },
    ],
    relatedSteps: ["LOAN", "SETTLEMENT"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["금리", "macro"],
    recommendedPeriod: ["Y1H2", "Y2H1", "Y2H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-006",
    title: "금리 인하 (경기 부양)",
    description: "경기 침체 대응 금리 cut.",
    category: "금리",
    educationPurpose: "레버리지 timing",
    learningPoints: ["레버리지 timing"],
    discussionQuestions: ["지금 투자(CAPEX) 확대?"],
    normalEffects: [
      { key: "interestRateLoan", mode: "DELTA", value: -2 },
      { key: "marketDemandIndex", mode: "PERCENT", value: 8 },
    ],
    relatedSteps: ["LOAN", "FACILITY"],
    severity: 1,
    difficulty: "EASY",
    tags: ["금리", "stimulus"],
    recommendedPeriod: ["Y1H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-009",
    title: "원자재 가격 급등",
    description: "commodity super cycle.",
    category: "원자재",
    educationPurpose: "Step4 구매·Step5 COGS",
    learningPoints: ["Step4 구매·Step5 COGS"],
    discussionQuestions: ["재고 선매 vs just-in-time?"],
    normalEffects: [{ key: "rawMaterialIndex", mode: "PERCENT", value: 25 }],
    relatedSteps: ["MATERIAL", "PRODUCTION"],
    severity: 3,
    difficulty: "HARD",
    tags: ["commodity", "COGS"],
    recommendedPeriod: ["Y1H2", "Y2H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-010",
    title: "석유·에너지 shock",
    description: "유가 상승, 물류·에너지비 전가.",
    category: "원자재",
    educationPurpose: "물류 5/10만과 연결",
    learningPoints: ["물류 5/10만과 연결"],
    discussionQuestions: ["판매가 전가 가능?"],
    normalEffects: [
      { key: "rawMaterialIndex", mode: "PERCENT", value: 15 },
      { key: "logisticsCostMultiplier", mode: "MULTIPLY", value: 1.25 },
    ],
    relatedSteps: ["MATERIAL", "SALES"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["energy", "logistics"],
    recommendedPeriod: ["Y2H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-013",
    title: "항만 파업",
    description: "major port strike, inbound delay.",
    category: "공급망",
    educationPurpose: "Step4→5 lead time",
    learningPoints: ["Step4→5 lead time"],
    discussionQuestions: ["domestic vs import mix?"],
    normalEffects: [
      { key: "logisticsCostMultiplier", mode: "MULTIPLY", value: 1.3 },
      { key: "marketSupplyIndex", mode: "PERCENT", value: -12 },
    ],
    relatedSteps: ["MATERIAL", "PRODUCTION"],
    severity: 3,
    difficulty: "NORMAL",
    tags: ["supply-chain", "logistics"],
    recommendedPeriod: ["Y2H1", "Y2H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-015",
    title: "Tier-2 공급사 부도",
    description: "supplier bankruptcy.",
    category: "공급망",
    educationPurpose: "counterparty risk",
    learningPoints: ["counterparty risk"],
    discussionQuestions: ["inventory buffer 정책?"],
    normalEffects: [
      { key: "marketSupplyIndex", mode: "PERCENT", value: -20 },
      { key: "rawMaterialIndex", mode: "PERCENT", value: 10 },
    ],
    relatedSteps: ["MATERIAL"],
    severity: 3,
    difficulty: "HARD",
    tags: ["supplier", "risk"],
    recommendedPeriod: ["Y2H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-020",
    title: "미·중 관세 25%",
    description: "US tariffs on imports (교육 시나리오).",
    category: "관세",
    educationPurpose: "trade war — 관세는 매출원가와 가격 전가의 trade-off",
    learningPoints: ["관세는 매출원가와 가격 전가의 trade-off", "공급망 다변화의 필요성"],
    discussionQuestions: ["국내 vs 수입 원재료 mix를 어떻게 바꿀 것인가?"],
    normalEffects: [
      { key: "tariffRate", mode: "ABSOLUTE", value: 25 },
      { key: "rawMaterialIndex", mode: "PERCENT", value: 10 },
      { key: "marketDemandIndex", mode: "PERCENT", value: -5 },
    ],
    relatedSteps: ["MATERIAL", "SALES"],
    severity: 3,
    difficulty: "NORMAL",
    tags: ["tariff", "trade"],
    recommendedPeriod: ["Y2H1", "Y2H2"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-021",
    title: "RCEP 관세 인하",
    description: "Asia trade pact, tariff cut.",
    category: "관세",
    educationPurpose: "FTA opportunity",
    learningPoints: ["FTA opportunity"],
    discussionQuestions: ["shift procurement to ASIA?"],
    normalEffects: [
      { key: "tariffRate", mode: "DELTA", value: -8 },
      { key: "marketDemandIndex", mode: "PERCENT", value: 6 },
    ],
    relatedSteps: ["MATERIAL"],
    severity: 1,
    difficulty: "EASY",
    tags: ["tariff", "FTA"],
    recommendedPeriod: ["Y1H2"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-046",
    title: "신규 저가 경쟁사 진입",
    description: "new entrant, price war.",
    category: "경쟁사",
    educationPurpose: "competitive strategy — margin vs share",
    learningPoints: ["competitive strategy"],
    discussionQuestions: ["margin vs share?"],
    normalEffects: [
      { key: "marketSupplyIndex", mode: "PERCENT", value: 20 },
      { key: "marketDemandIndex", mode: "PERCENT", value: -5 },
    ],
    relatedSteps: ["SALES"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["competition"],
    recommendedPeriod: ["Y2H2", "Y3H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-049",
    title: "경쟁사 파산 — share available",
    description: "competitor exit.",
    category: "경쟁사",
    educationPurpose: "opportunity from distress",
    learningPoints: ["opportunity from distress"],
    discussionQuestions: ["capacity to capture?"],
    normalEffects: [{ key: "marketDemandIndex", mode: "PERCENT", value: 15 }],
    relatedSteps: ["SALES", "PRODUCTION"],
    severity: 1,
    difficulty: "EASY",
    tags: ["competition", "opportunity"],
    recommendedPeriod: ["Y3H1"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-050",
    title: "법인세 인상",
    description: "fiscal consolidation.",
    category: "정부정책",
    educationPurpose: "Step7 tax line",
    learningPoints: ["Step7 tax line"],
    discussionQuestions: ["pre-tax vs after-tax decision?"],
    normalEffects: [{ key: "corporateTaxRate", mode: "DELTA", value: 5 }],
    relatedSteps: ["SETTLEMENT"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["tax", "policy"],
    recommendedPeriod: ["Y1H2", "Y2H1"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-051",
    title: "제조업 보조금",
    description: "industrial policy subsidy.",
    category: "정부정책",
    educationPurpose: "industrial policy",
    learningPoints: ["industrial policy"],
    discussionQuestions: ["accelerate Step2?"],
    normalEffects: [{ key: "marketDemandIndex", mode: "PERCENT", value: 5 }],
    relatedSteps: ["FACILITY", "SALES"],
    severity: 1,
    difficulty: "EASY",
    tags: ["subsidy", "policy"],
    recommendedPeriod: ["Y1H2"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "INSTANT",
  },
  {
    eventId: "EVT-052",
    title: "최저임금·노동법 강화",
    description: "labor cost up.",
    category: "정부정책",
    educationPurpose: "Step3 commitment",
    learningPoints: ["Step3 commitment"],
    discussionQuestions: ["automation vs hire?"],
    normalEffects: [{ key: "payrollCostMultiplier", mode: "MULTIPLY", value: 1.15 }],
    relatedSteps: ["SETTLEMENT"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["labor", "policy"],
    recommendedPeriod: ["Y2H1"],
    avoidPeriod: [],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-039",
    title: "대지진 — 공장 가동 중단",
    description: "earthquake, production halt 半기.",
    category: "자연재해",
    educationPurpose: "business continuity",
    learningPoints: ["business continuity"],
    discussionQuestions: ["insurance vs redundancy?"],
    normalEffects: [
      { key: "techInnovationIndex", mode: "PERCENT", value: -40 },
      { key: "logisticsCostMultiplier", mode: "MULTIPLY", value: 1.2 },
    ],
    relatedSteps: ["PRODUCTION"],
    severity: 4,
    difficulty: "HARD",
    tags: ["disaster", "production"],
    recommendedPeriod: ["Y2H1", "Y2H2", "Y3H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-040",
    title: "홍수 — 공급망 침수",
    description: "flood destroys supplier region.",
    category: "자연재해",
    educationPurpose: "disaster recovery",
    learningPoints: ["disaster recovery"],
    discussionQuestions: ["alternate regions in Step4?"],
    normalEffects: [
      { key: "marketSupplyIndex", mode: "PERCENT", value: -25 },
      { key: "rawMaterialIndex", mode: "PERCENT", value: 15 },
    ],
    relatedSteps: ["MATERIAL"],
    severity: 3,
    difficulty: "HARD",
    tags: ["disaster", "supply"],
    recommendedPeriod: ["Y2H1"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "PERIOD",
  },
  {
    eventId: "EVT-042",
    title: "태풍 — 항만 closure",
    description: "typhoon season port close.",
    category: "자연재해",
    educationPurpose: "seasonality",
    learningPoints: ["seasonality"],
    discussionQuestions: ["timing purchases?"],
    normalEffects: [{ key: "logisticsCostMultiplier", mode: "MULTIPLY", value: 1.4 }],
    relatedSteps: ["MATERIAL", "SALES"],
    severity: 2,
    difficulty: "NORMAL",
    tags: ["disaster", "logistics"],
    recommendedPeriod: ["Y2H2"],
    avoidPeriod: ["Y1H1"],
    maxSeverityInAvoid: 3,
    duration: "INSTANT",
  },
];

const catalogById = new Map(EVENT_CATALOG.map((e) => [e.eventId, e]));

export function getEventTemplate(eventId: string): EventTemplate | undefined {
  return catalogById.get(eventId);
}

export function listEventCatalog(filter?: { search?: string; category?: string }): EventTemplate[] {
  let items = [...EVENT_CATALOG];
  if (filter?.category) {
    items = items.filter((e) => e.category === filter.category);
  }
  if (filter?.search) {
    const q = filter.search.toLowerCase();
    items = items.filter(
      (e) =>
        e.eventId.toLowerCase().includes(q) ||
        e.title.toLowerCase().includes(q) ||
        e.description.toLowerCase().includes(q) ||
        e.tags.some((t) => t.toLowerCase().includes(q))
    );
  }
  return items;
}

export function listEventCategories(): EventCategory[] {
  return [...new Set(EVENT_CATALOG.map((e) => e.category))];
}
